name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write #  to fetch code (actions/checkout)

jobs:
  build-and-verify:
    name: Build and verify (JDK 8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # at least support HEAD~1 for testing
          fetch-depth: 2
      - name: Download Maven # Download with default JDK because OpenJDK 6 does not support TLS 1.2
        run: ./mvnw --version

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: temurin

      - name: Build and verify
        run: ./mvnw clean verify javadoc:javadoc site:site --batch-mode --errors --settings .github/workflows/settings.xml

      - name: diffctx
        uses: williamfzc/diffctx@v0.3.8
        with:
          lang: java
          # https://sourcegraph.github.io/scip-java/docs/getting-started.html#run-scip-java-index
          index_cmd: scip-java index -- package -DskipTests --batch-mode --errors --settings .github/workflows/settings.xml
